config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'user_bookings', to: 'bookings#index', as: 'user_bookings'
  resources :hotels, only: %i[index show] do
    resources :rooms, except: %i[edit update] do
      resources :bookings, only: %i[index create destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :starts_at, presence: true
  validates :ends_at, presence: true
  
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  has_one_attached :image

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :capacity, presence: true
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }
  validates :price_per_night, presence: true
  validates :price_per_night, numericality: { only_integer: true, greater_than: 0 }
  has_one_attached :image


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
    @dates = @bookings.map { |booking| (booking.starts_at - Date.today).to_i }
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
  end

  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.js { flash.now[:success] = 'Booking was successfully created.' }
        format.turbo_stream
      else
        format.js { flash.now[:error] = 'There was an error creating the booking.' }
        format.turbo_stream
      end
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_back(fallback_location: request.referer)
  end

  private

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at, :room_id, :user_id)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    if params[:search] && params[:search][:city].present?
      @search_params = search_params.to_h
      @search_params[:start_date], @search_params[:end_date] = @search_params[:start_date].split(' au ')
      @hotels = Hotel.joins(:rooms).where('city ILIKE ?', "%#{@search_params[:city]}%").where('rooms.capacity >= ?', @search_params[:capacity]).distinct
      hotel = Hotel.find_by('city ILIKE ?', "%#{@search_params[:city]}%")
      if hotel
        @city = hotel.city
      else
        respond_to do |format|
          format.html { redirect_to request.referrer || root_path, alert: "La ville n'est pas trouvée." }
          format.js { render js: "Swal.fire('Erreur', 'La ville n\'est pas trouvée.', 'error')" }
        end
        return
      end
      @search_params[:city] = @city
    else
      @hotels = Hotel.all
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
    redirect_to hotels_path
  end

  private
  def search_params
    params.require(:search).permit(:city, :capacity, :start_date, :end_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @hotels = Hotel.all
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @search_params = params[:search] || {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
 <div class="reservation-container">
<h2 class="reservation-title">Vos réservations</h2>
		<h3 class="reservation-subtitle">Consultez,  annulez vos réservations en un clin d'œil.</h3>
 </div>


<div class="grid-container2">

  <% @bookings.each do |booking| %>
    <% if (booking.starts_at.to_date - Date.today).to_i >= 0 %>
      <div class="card">
        <div class="card-img">
          <%= cl_image_tag booking.room.image.key,
          :width => 226, :height => 129,
          class: "card-img" if booking.room.image.present? %>
        </div>
        <div class="card-title"><%= booking.room.hotel.name %></div>

        <div class="card-footer specformat">
          <p class="card-subtitle"> Du <span class="date">  <%= l(booking.starts_at, format: :long) %></span></p>
          <p class="card-subtitle"> Au <span class="date">  <%= l(booking.ends_at, format: :long) %></span></p>
          <p class="card-subtitle">Nombre de jours avant: <span class="date"><%= (booking.starts_at.to_date - Date.today).to_i %></span></p>
          <%= link_to hotel_room_booking_path(booking.room.hotel, booking.room, booking), data: { turbo_method: :delete } , method: :delete, class: "button" do %>
            <svg viewBox="0 0 448 512" class="svgIcon"><path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"></path></svg>

          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/hotels/index.html.erb
<div class="container", style="position: relative;
    bottom: 34px;">
<%= render 'pages/search' %>
</div>


<div class="grid-container">
  <% @hotels.each do |hotel| %>
    <div class="card">
      <div class="card-img">
          <%= cl_image_tag hotel.image.key,

            class: "card-img" if hotel.image.present? %>
      </div>
      <div class="card-title"><%=hotel.city%>, <%= hotel.name %></div>
      <div class="card-subtitle"><%= hotel.address %></div>

      <div class="card-footer">
        <% hotel.rooms.each do |room| %>
          <%= link_to hotel_room_path(room.hotel, room, search: @search_params), class: "card-btn" do %>
            <div class="card-price"><%= room.price_per_night %><span>€/par nuit</span> </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arc</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="shortcut icon" type="image/png" href="<%= asset_path('arcsmall.png') %>"/>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Aguafina+Script&display=swap" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
  <%= render "shared/flashes" %>

    <%= yield %>
    <%= render 'pages/footer' %>
  </body>
</html>

app/views/pages/_footer.html.erb
<footer class="text-center">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Images -->
    <section class="">
      <% cities = ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille"] %>
      

      <% cities.each_slice(5).with_index do |city_group, index| %>
  <div class="row justify-content-center">
    <% city_group.each_with_index do |city, i| %>
      <div class="col-lg-2 col-md-4 col-sm-6 mb-4">
        <div class="bg-image shadow-1-strong rounded">
          <a href="<%= "https://www.google.com/search?q=" + city + "&source=lnms&tbm=isch" %>" target="_blank">
            <img src="<%= "https://source.unsplash.com/1600x900/?france,city," + city.downcase %>" alt="<%= city %>" class="img-fluid" />
          </a>
        </div>
        <h5 class="text-center"><%= city %></h5>
      </div>
    <% end %>
  </div>
<% end %>
    </section>
    <!-- Section: Images -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3">
    © 2024 Copyright:
    <a class="text-body" href="https://github.com/Bnoure">By Nour-Eddine Benkerroum </a>
  </div>
  <!-- Copyright -->
</footer>

app/views/pages/_search.html.erb
<%# Recherche pas case sensitive %>
<div class="search">
    <%= simple_form_for :search, url: hotels_path, method: :get, html: { class: "fomrme", id: "search-form", onsubmit: "return validateForm();" } do |f| %>
  <div class="row">
    <div class="col-md-3">
      <%= f.input :city, label: "Localisation", input_html: { id: "city-input", class: "form-control", placeholder: "Ville" }, name: 'search[city]' %>
    </div>
    <div class="col-md-3">
      <%= f.input :capacity, collection: 1..8, label: "Nombre de personnes", input_html: { id: "capacity-input", class: "form-control select" } %>
    </div>
    <div class="col-md-3">
      <%= f.input :start_date, label: "Votre séjour ", input_html: { id: "start-date-input", class: "form-control", placeholder: "Vos dates", type: "text", data: { controller: "flatpickr" } } %>
    </div>
    <div class="col-md-3 maclassebut">
      <div id="date-difference"></div>
      <%= f.button :submit, "Rechercher", class: "monbutton" %>
    </div>
    <%= f.input :end_date, as: :hidden, input_html: { id: "end-date-input" } %>
  </div>

<% end %>
  </div>

app/views/pages/home.html.erb
<div class="container", style="gap: 66px;">
  <div class="imaghero">
    <%= image_tag("immeuble.png", class: "imb") %>
  </div>
  <div class="herotext">
    <h1 class="headline">Hôtel pour des <br>riches en émotions</h1>
    <h1 class="memorable">Moments mémorables</h1>
    <p class="subtitre">Nous avons <strong> plus de 200 chambres</strong> réparties à travers la France, avec des standards de chambre équivalents à des hôtels 5 étoiles.</p>
  </div>

  <%= render 'search' %>
</div>

app/views/rooms/show.html.erb
<div class="formatroom">
  <div class="Hero-hotel-room">
  <% if @search_params && @search_params[:start_date].present? && @search_params[:end_date].present? %>
  <% start_date = Date.strptime(@search_params[:start_date], '%d-%m-%Y') %>
  <% end_date = Date.strptime(@search_params[:end_date], '%d-%m-%Y') %>
  <% number_of_days = (end_date - start_date).to_i %>
  <% total_price = number_of_days * @room.price_per_night %>

  <div class="room-details">
    <div class="photohotelroom">
      <%= cl_image_tag @room.image.key, class:"roomimg" %>
    </div>

    <div class="reservation-summary">
      <p class="intro-text">Veuillez vérifier les informations ci-dessous avant de procéder à la réservation.</p>
      <h2>Récapitulatif de votre réservation</h2>
      <ul>
        <li><strong>Ville :</strong> <span class="variable"><%= @search_params[:city] %></span></li>
        <li><strong>Nombre de personnes :</strong> <span class="variable"><%= @search_params[:capacity] %></span></li>
        <li><strong>Date de début :</strong> <span class="variable"><%= @search_params[:start_date] %></span></li>
        <li><strong>Date de fin :</strong> <span class="variable"> <%= @search_params[:end_date] %></span></li>
        <li><strong>Nombre de jours :</strong> <span class="variable"><%= number_of_days %></span></li>
        <li><strong>Prix total :</strong> <span class="variable"><%= total_price %> €</span></li>
      </ul>
      <div class="footi">
        <div class="reservation-section">
        <%= simple_form_for Booking.new, url: hotel_room_bookings_path(@room.hotel, @room), method: :post, data: { controller: "booking", booking_target: "form", turbo_frame: "_top", action: "submit->booking#submit" } do |f| %>
      <%= f.input :room_id, as: :hidden, input_html: { value: @room.id } %>
      <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
      <%= f.input :starts_at, as: :hidden, input_html: { value: @search_params[:start_date] } %>
      <%= f.input :ends_at, as: :hidden, input_html: { value: @search_params[:end_date] } %>
      <%= f.button :submit, "Réserver", class: "btn" %>
    <% end %>
      </div>
      </div>
      <p class="footer-text">Si vous avez des questions ou des demandes spéciales, n'hésitez pas à nous contacter.</p>
    </div>
  </div>
  <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Accueil", root_path, class: "nav-link", style: "padding-right: 20px; font-size: 18px; margin-top: 20px; " %>
          </li>
          <li class="nav-item active">
            <%= link_to "Vos réservations", user_bookings_path, class: "nav-link", style: "padding-right: 20px; font-size: 18px; margin-top: 20px;" %>
          </li>
          <div class="about" data-controller="modal">
            <!-- ... -->
            <li>
              <button class="nav-link" style="padding-right: 20px; font-size: 18px; margin-top: 20px;border: none" data-action="click->modal#open">À propos </button>
              <dialog id="dialog" data-modal-target="dialog">
                <div class="modal-content">
                  <%= image_tag "nour.jpg", class:"avatarNour"%>
                  <h3 style="display: flex; align-items: center; justify-content: center;">👋 Hey, je suis Nour-Eddine Benkerroum</h3>
                  <p>🚀 Passionné par le développement web, Je poursuis ma passion pour le développement web après avoir complété ma formation chez Le Wagon, me préparant à embrasser pleinement la carrière de développeur full stack. Fort d'une expérience antérieure en tant que chef de projet IT, j'ai décidé de changer de cap pour embrasser pleinement le monde du développement. Mon objectif est d'acquérir une expertise solide dans l'écosystème JavaScript, en me concentrant sur React, TypeScript, Node.js, et plus encore.</p>
                  <hr>
                  <h4>🌱 Ce que j'apprends actuellement</h4>
                  <ul>
                    <li>JavaScript: Découverte des fondamentaux et des concepts avancés pour des applications interactives.</li>
                    <li>React: Immersion dans la création d'interfaces utilisateur dynamiques et réactives.</li>
                    <li>TypeScript: Apprentissage de ce langage pour renforcer la qualité et la maintenabilité du code.</li>
                    <li>Node.js: Exploration de l'environnement serveur pour développer des applications web complètes.</li>
                  </ul>
                  <hr>
                  <h4>🎯 Mes intérêts</h4>
                  <ul>
                    <li>Développement Full Stack: Aspirer à devenir un développeur versatile capable de travailler à la fois sur le front-end et le back-end.</li>
                    <li>Ecosystème JavaScript: Se spécialiser dans l'écosystème JS pour créer des applications modernes et performantes.</li>
                    <li>Ruby on Rails: Approfondir mes connaissances et compétences en Ruby on Rails pour développer des applications web dynamiques et évolutives.</li>
                    <li>Apprentissage Continu: Reste à l'affût des dernières technologies et meilleures pratiques en développement web.</li>
                  </ul>
                  <hr>
                  <h4>📫 Me contacter</h4>
                  <ul>
                    <li><a href="mailto:noureddine.benkerroum@gmail.com">Mail</a></li>
                    <li><a href="https://www.linkedin.com/in/nbenkerroum/">Linkedin</a></li>
                  </ul>
                  <button data-action="click->modal#close" data-modal-target="x" aria-label="close" class="x">❌</button>
                </div>
              </dialog>
            </li>
            <!-- ... -->
          </div>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.avatar.attached? %>
                <%= cl_image_tag current_user.avatar.key, class: "avatar", alt: "dropdown menu" %>
              <% else %>
                <%= image_tag "https://i.pravatar.cc/300", class: "avatar", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%#= link_to "Action", "#", class: "dropdown-item" %>
              <%#= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="font-size: larger">
              <span style="font-size: 10px"> </span>Connexion
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= form_for(User.new, url: user_session_path) do |f| %>
                <div class="mb-3">
                  <%= f.label :email, class: "form-label", style: "font-size: larger" %>
                  <%= f.email_field :email, class: "form-control", style: "width: 190%;" %>
                </div>
                <div class="mb-3">
                  <%= f.label :password, class: "form-label", style: "font-size: larger" %>
                  <%= f.password_field :password, class: "form-control", style: "width: 190%;" %>
                </div>
                <%= f.submit "Se connecter", class: "custom-button", style: "margin-left: 68%; height: 22%; width: 77%;" %>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>